ControlNode:
  ros__parameters:
    # simulation
    # STANLEY_CTE: 1.0
    # MAX_STEER_ANGLE: 0.6
    # WHEEL_BASE: 0.26
    # PURE_PERSUIT_LOOKAHEAD_DIS: 2.0
    # DS: 0.2
    # MAX_DIS_DRONE_FROM_TRAJ: 0.7


    STANLEY_CTE: 0.8
    MAX_STEER_ANGLE: 0.6
    WHEEL_BASE: 0.26
    LOOKAHEAD_DIS: 0.5
    DS: 0.2
    MAX_DIS_DRONE_FROM_TRAJ: 0.7
    PURE_PERSUIT_CTE: 1.5
    YAW_K_GAIN: 1.0
    MAX_ANGULAR: 2.0
    CROSS_TRACK_KP: 0.5
    CROSS_TRACK_KI: 0.0
    CROSS_TRACK_KD: 0.4
    MAX_LATERAL: 0.3
    WALL_AVOID_K_GAIN: 1.0
    MAX_WALL_LATERAL: 0.3









 




