LocalPlannerNode:
  ros__parameters:
    # drone kinematics
    COLLISION_R: 0.25
    WHEEL_BASE: 0.26
    COLLISION_PNTS: [0.0, 0.2]
    MAX_STEER_ANGLE_DEG: 90.0
    REVERSE_MAX_STEER_ANGLE: 20.0

    # local planner params
    HEURISTIC_GAIN: 1.0
    K_GEAR_CHANGE_COST: 1.0
    DOWNSAMPLE_RATIO: 2.0
    DS: 0.4
    GOAL_TOLERANCE: 0.4
    D_COST: 0.3
    DO_PREEMPT: true
    TIMEOUT: 0.3
    UNSTRUCTURED_TIMEOUT: 10.0
    YAWE_COST: 0.6
    YAW_TOLERANCE: 0.3
    MIN_SEGMENT_LEN: 0.5
    MAX_SEGMENTS_NUM: 10
    END_TOLERANCE: 0.4
    CLEARANCE_COST: 0.4
    MAX_FORWARD_LEN: 10.0

