Manager:
  ros__parameters:
    # drone kinematics
    COLLISION_R: 0.5
    ESP_COLLISION_R: 0.15
    COLLISION_PNTS: [0.0]
    END_TOLERANCE: 5.0
    ASTAR_TIMEOUT_SEC: 5.0
    ASTAR_STEP_SIZE: 10

  

